services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: raider-mate
      POSTGRES_PASSWORD: raider-mate
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raider-mate"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
