// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attendanceByCharacter = `-- name: AttendanceByCharacter :many
SELECT
    c.id                                                     AS character_id,
    c.name,
    c.realm,
    c.class,
    count(*) FILTER (WHERE s.status = 'CONFIRMED')::bigint    AS confirmed,
    count(*) FILTER (WHERE s.status = 'TENTATIVE')::bigint    AS tentative,
    count(*) FILTER (WHERE s.status = 'DECLINED')::bigint     AS declined,
    count(*) FILTER (WHERE s.status = 'LATE')::bigint         AS late,
    count(*) FILTER (WHERE s.status = 'ABSENT')::bigint       AS absent,
    count(*) FILTER (WHERE s.status = 'NO_SHOW')::bigint      AS no_show
FROM signups s
JOIN events e ON e.id = s.event_id
JOIN characters c ON c.id = s.character_id
WHERE e.discord_guild_id = $1
  AND e.starts_at >= $2
  AND e.starts_at < $3
GROUP BY c.id, c.name, c.realm, c.class
ORDER BY c.name, c.realm
`

type AttendanceByCharacterParams struct {
	GuildID int64
	Since   pgtype.Timestamptz
	Until   pgtype.Timestamptz
}

type AttendanceByCharacterRow struct {
	CharacterID uuid.UUID
	Name        string
	Realm       string
	Class       *string
	Confirmed   int64
	Tentative   int64
	Declined    int64
	Late        int64
	Absent      int64
	NoShow      int64
}

// One row per character that answered at least once in the window, with the statuses
// split out rather than summed. NO_SHOW and DECLINED are the pair that matters: since
// 0.7.0 a raid lead may write NO_SHOW and nothing else on someone else's signup, so
// "said no in advance" and "did not turn up" are finally different facts.
func (q *Queries) AttendanceByCharacter(ctx context.Context, arg AttendanceByCharacterParams) ([]AttendanceByCharacterRow, error) {
	rows, err := q.db.Query(ctx, attendanceByCharacter, arg.GuildID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceByCharacterRow
	for rows.Next() {
		var i AttendanceByCharacterRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Confirmed,
			&i.Tentative,
			&i.Declined,
			&i.Late,
			&i.Absent,
			&i.NoShow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const benchByCharacter = `-- name: BenchByCharacter :many
SELECT
    c.id                                            AS character_id,
    c.name,
    c.realm,
    c.class,
    count(*)::bigint                                AS boards,
    count(*) FILTER (WHERE cs.is_bench)::bigint     AS benched
FROM comp_slots cs
JOIN events e ON e.id = cs.event_id
JOIN characters c ON c.id = cs.character_id
WHERE e.discord_guild_id = $1
  AND e.starts_at >= $2
  AND e.starts_at < $3
GROUP BY c.id, c.name, c.realm, c.class
ORDER BY benched DESC, c.name, c.realm
`

type BenchByCharacterParams struct {
	GuildID int64
	Since   pgtype.Timestamptz
	Until   pgtype.Timestamptz
}

type BenchByCharacterRow struct {
	CharacterID uuid.UUID
	Name        string
	Realm       string
	Class       *string
	Boards      int64
	Benched     int64
}

// The bench fairness tracker. Ordered by how often somebody sat out, because the
// question this answers is always "who has been carrying the bench".
func (q *Queries) BenchByCharacter(ctx context.Context, arg BenchByCharacterParams) ([]BenchByCharacterRow, error) {
	rows, err := q.db.Query(ctx, benchByCharacter, arg.GuildID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BenchByCharacterRow
	for rows.Next() {
		var i BenchByCharacterRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Boards,
			&i.Benched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compRoleTotals = `-- name: CompRoleTotals :many
SELECT
    cs.role,
    count(*) FILTER (WHERE NOT cs.is_bench)::bigint AS placed,
    count(*) FILTER (WHERE cs.is_bench)::bigint     AS benched
FROM comp_slots cs
JOIN events e ON e.id = cs.event_id
WHERE e.discord_guild_id = $1
  AND e.starts_at >= $2
  AND e.starts_at < $3
GROUP BY cs.role
ORDER BY cs.role
`

type CompRoleTotalsParams struct {
	GuildID int64
	Since   pgtype.Timestamptz
	Until   pgtype.Timestamptz
}

type CompRoleTotalsRow struct {
	Role    RoleEnum
	Placed  int64
	Benched int64
}

// What the guild actually fielded, by role, across every comp in the window. Roster
// and bench counted apart: a role that is always on the bench is oversupplied, and a
// combined total hides exactly that.
func (q *Queries) CompRoleTotals(ctx context.Context, arg CompRoleTotalsParams) ([]CompRoleTotalsRow, error) {
	rows, err := q.db.Query(ctx, compRoleTotals, arg.GuildID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompRoleTotalsRow
	for rows.Next() {
		var i CompRoleTotalsRow
		if err := rows.Scan(&i.Role, &i.Placed, &i.Benched); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventsInWindow = `-- name: CountEventsInWindow :one

SELECT count(*)::bigint FROM events
WHERE discord_guild_id = $1
  AND starts_at >= $2
  AND starts_at < $3
`

type CountEventsInWindowParams struct {
	GuildID int64
	Since   pgtype.Timestamptz
	Until   pgtype.Timestamptz
}

// Every query here is bounded by an explicit window rather than by now(): the cutoff
// and the upper bound both arrive as parameters so a test can pin the clock, and so
// one request's panels all describe the same stretch of time.
// The denominator every attendance percentage divides by. Counted once rather than
// per character, because a raider who signed up to nothing has no rows to count and
// would otherwise vanish from their own attendance rate.
func (q *Queries) CountEventsInWindow(ctx context.Context, arg CountEventsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsInWindow, arg.GuildID, arg.Since, arg.Until)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const eventThroughput = `-- name: EventThroughput :many
SELECT
    date_trunc('week', e.starts_at)::timestamptz                                   AS week,
    count(DISTINCT e.id)::bigint                                                   AS events,
    count(DISTINCT s.character_id) FILTER (WHERE s.status = 'CONFIRMED')::bigint   AS confirmed,
    count(DISTINCT s.character_id) FILTER (WHERE s.status = 'DECLINED')::bigint    AS declined,
    count(DISTINCT s.character_id) FILTER (WHERE s.status = 'NO_SHOW')::bigint     AS no_show,
    count(DISTINCT cs.character_id) FILTER (WHERE NOT cs.is_bench)::bigint         AS placed,
    count(DISTINCT cs.character_id) FILTER (WHERE cs.is_bench)::bigint             AS benched
FROM events e
LEFT JOIN signups s ON s.event_id = e.id
LEFT JOIN comp_slots cs ON cs.event_id = e.id
WHERE e.discord_guild_id = $1
  AND e.starts_at >= $2
  AND e.starts_at < $3
GROUP BY week
ORDER BY week
`

type EventThroughputParams struct {
	GuildID int64
	Since   pgtype.Timestamptz
	Until   pgtype.Timestamptz
}

type EventThroughputRow struct {
	Week      pgtype.Timestamptz
	Events    int64
	Confirmed int64
	Declined  int64
	NoShow    int64
	Placed    int64
	Benched   int64
}

// Weekly, and counted in people rather than in rows.
//
// A bar is a week, and a week holds however many raids the guild ran. Summing each
// raid's signups made twelve raiders across three nights read as thirty-six, which is
// more people than the guild has and more than the roster it is drawn beside.
//
// count(DISTINCT character_id) is also what lets signups and comp_slots hang off the
// same row without multiplying each other: the join duplicates rows, and the distinct
// collapses them back. That is why this reads as a plain join rather than the pair of
// laterals it needed when it was summing.
func (q *Queries) EventThroughput(ctx context.Context, arg EventThroughputParams) ([]EventThroughputRow, error) {
	rows, err := q.db.Query(ctx, eventThroughput, arg.GuildID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventThroughputRow
	for rows.Next() {
		var i EventThroughputRow
		if err := rows.Scan(
			&i.Week,
			&i.Events,
			&i.Confirmed,
			&i.Declined,
			&i.NoShow,
			&i.Placed,
			&i.Benched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ilvlSeries = `-- name: IlvlSeries :many
WITH weekly AS (
    SELECT DISTINCT ON (sn.character_id, date_trunc('week', sn.captured_at))
        date_trunc('week', sn.captured_at)::timestamptz AS week,
        sn.character_id,
        sn.ilvl
    FROM character_snapshots sn
    JOIN characters c ON c.id = sn.character_id
    JOIN users u ON u.id = c.user_id
    WHERE u.discord_guild_id = $1
      AND c.is_main
      AND sn.captured_at >= $2
      AND sn.captured_at < $3
      AND sn.ilvl IS NOT NULL
    ORDER BY sn.character_id, date_trunc('week', sn.captured_at), sn.captured_at DESC, sn.id DESC
)
SELECT
    week,
    count(*)::bigint AS characters,
    (percentile_cont(0.25) WITHIN GROUP (ORDER BY ilvl::double precision))::double precision AS p25_ilvl,
    (percentile_cont(0.5) WITHIN GROUP (ORDER BY ilvl::double precision))::double precision AS median_ilvl,
    (percentile_cont(0.75) WITHIN GROUP (ORDER BY ilvl::double precision))::double precision AS p75_ilvl
FROM weekly
GROUP BY week
ORDER BY week
`

type IlvlSeriesParams struct {
	GuildID int64
	Since   pgtype.Timestamptz
	Until   pgtype.Timestamptz
}

type IlvlSeriesRow struct {
	Week       pgtype.Timestamptz
	Characters int64
	P25Ilvl    float64
	MedianIlvl float64
	P75Ilvl    float64
}

// Mains only, and quartiles rather than extremes.
//
// Both are the same fix for the same thing. A guild's roster holds abandoned alts and
// half-levelled bank characters, so min over every character is whichever level-20 was
// registered and never touched again, and a band drawn from it spans two hundred item
// levels of nothing. A raider's main is what the guild actually raids with, and the
// middle half of those is a spread that one returning player cannot move.
//
// A sync writes a row whenever Raider.IO moved, so a character who reforged four times
// in a week would otherwise weigh four times as much as one who logged off: DISTINCT ON
// takes that character's last snapshot in each week, and the aggregate then sees one row
// per character per week.
//
// double precision rather than numeric because these are summary statistics being drawn
// as a chart, and pgtype.Numeric buys nothing at the far end of that.
func (q *Queries) IlvlSeries(ctx context.Context, arg IlvlSeriesParams) ([]IlvlSeriesRow, error) {
	rows, err := q.db.Query(ctx, ilvlSeries, arg.GuildID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IlvlSeriesRow
	for rows.Next() {
		var i IlvlSeriesRow
		if err := rows.Scan(
			&i.Week,
			&i.Characters,
			&i.P25Ilvl,
			&i.MedianIlvl,
			&i.P75Ilvl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleCoverage = `-- name: RoleCoverage :many
SELECT
    cr.role,
    count(*)::bigint                                  AS characters,
    count(*) FILTER (WHERE cr.priority = 1)::bigint   AS first_choice
FROM character_roles cr
JOIN characters c ON c.id = cr.character_id
JOIN users u ON u.id = c.user_id
WHERE u.discord_guild_id = $1
GROUP BY cr.role
ORDER BY cr.role
`

type RoleCoverageRow struct {
	Role        RoleEnum
	Characters  int64
	FirstChoice int64
}

// What the roster CAN play, which is the roles on the character and not the roles a
// comp happened to use. Priority 1 counted separately: a guild with nine healers who
// would all rather be dps is not a guild with nine healers.
func (q *Queries) RoleCoverage(ctx context.Context, guildID int64) ([]RoleCoverageRow, error) {
	rows, err := q.db.Query(ctx, roleCoverage, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleCoverageRow
	for rows.Next() {
		var i RoleCoverageRow
		if err := rows.Scan(&i.Role, &i.Characters, &i.FirstChoice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rosterActivity = `-- name: RosterActivity :one
SELECT
    count(*)::bigint                                              AS characters,
    count(*) FILTER (WHERE c.is_main)::bigint                     AS mains,
    count(*) FILTER (WHERE active.character_id IS NOT NULL)::bigint AS active
FROM characters c
JOIN users u ON u.id = c.user_id
LEFT JOIN (
    SELECT DISTINCT s.character_id
    FROM signups s
    JOIN events e ON e.id = s.event_id
    WHERE e.discord_guild_id = $1
      AND e.starts_at >= $2
      AND e.starts_at < $3
) active ON active.character_id = c.id
WHERE u.discord_guild_id = $1
`

type RosterActivityParams struct {
	GuildID int64
	Since   pgtype.Timestamptz
	Until   pgtype.Timestamptz
}

type RosterActivityRow struct {
	Characters int64
	Mains      int64
	Active     int64
}

// Roster size against how much of it is still turning up. Dormant is the difference,
// computed by the caller rather than selected, so the two numbers cannot disagree.
func (q *Queries) RosterActivity(ctx context.Context, arg RosterActivityParams) (RosterActivityRow, error) {
	row := q.db.QueryRow(ctx, rosterActivity, arg.GuildID, arg.Since, arg.Until)
	var i RosterActivityRow
	err := row.Scan(&i.Characters, &i.Mains, &i.Active)
	return i, err
}
