// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestCharacterSnapshot = `-- name: GetLatestCharacterSnapshot :one
SELECT id, character_id, captured_at, ilvl, mplus_score, gear FROM character_snapshots
WHERE character_id = $1
ORDER BY captured_at DESC, id DESC
LIMIT 1
`

// captured_at is transaction start time, so it ties for snapshots written in the
// same transaction; id (UUIDv7) breaks the tie in insertion order.
func (q *Queries) GetLatestCharacterSnapshot(ctx context.Context, characterID uuid.UUID) (CharacterSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestCharacterSnapshot, characterID)
	var i CharacterSnapshot
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.CapturedAt,
		&i.Ilvl,
		&i.MplusScore,
		&i.Gear,
	)
	return i, err
}

const insertCharacterSnapshot = `-- name: InsertCharacterSnapshot :one
INSERT INTO character_snapshots (character_id, ilvl, mplus_score, gear)
VALUES ($1, $2, $3, $4)
RETURNING id, character_id, captured_at, ilvl, mplus_score, gear
`

type InsertCharacterSnapshotParams struct {
	CharacterID uuid.UUID
	Ilvl        pgtype.Numeric
	MplusScore  pgtype.Numeric
	Gear        []byte
}

func (q *Queries) InsertCharacterSnapshot(ctx context.Context, arg InsertCharacterSnapshotParams) (CharacterSnapshot, error) {
	row := q.db.QueryRow(ctx, insertCharacterSnapshot,
		arg.CharacterID,
		arg.Ilvl,
		arg.MplusScore,
		arg.Gear,
	)
	var i CharacterSnapshot
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.CapturedAt,
		&i.Ilvl,
		&i.MplusScore,
		&i.Gear,
	)
	return i, err
}
