// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscription = `-- name: GetSubscription :one
SELECT id, discord_guild_id, tier, billing_period, provider_sub_id, status, price_locked_at, current_period_end, updated_at FROM subscriptions
WHERE discord_guild_id = $1
`

// No row is not an error to the caller: internal/billing reads pgx.ErrNoRows as FREE,
// which is what a guild that has never subscribed is.
func (q *Queries) GetSubscription(ctx context.Context, discordGuildID int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, discordGuildID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.DiscordGuildID,
		&i.Tier,
		&i.BillingPeriod,
		&i.ProviderSubID,
		&i.Status,
		&i.PriceLockedAt,
		&i.CurrentPeriodEnd,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    id, discord_guild_id, tier, billing_period, provider_sub_id, status,
    price_locked_at, current_period_end
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (discord_guild_id) DO UPDATE SET
    tier               = excluded.tier,
    billing_period     = excluded.billing_period,
    provider_sub_id    = excluded.provider_sub_id,
    status             = excluded.status,
    price_locked_at    = excluded.price_locked_at,
    current_period_end = excluded.current_period_end,
    updated_at         = now()
RETURNING id, discord_guild_id, tier, billing_period, provider_sub_id, status, price_locked_at, current_period_end, updated_at
`

type UpsertSubscriptionParams struct {
	ID               uuid.UUID
	DiscordGuildID   int64
	Tier             TierEnum
	BillingPeriod    *BillingPeriodEnum
	ProviderSubID    *string
	Status           SubStatusEnum
	PriceLockedAt    pgtype.Numeric
	CurrentPeriodEnd pgtype.Timestamptz
}

// No HTTP route writes this yet. It exists so the tier can be set from a migration,
// a console, or the billing webhooks that come later, without a second shape to keep
// in step with the one internal/billing reads.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.ID,
		arg.DiscordGuildID,
		arg.Tier,
		arg.BillingPeriod,
		arg.ProviderSubID,
		arg.Status,
		arg.PriceLockedAt,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.DiscordGuildID,
		&i.Tier,
		&i.BillingPeriod,
		&i.ProviderSubID,
		&i.Status,
		&i.PriceLockedAt,
		&i.CurrentPeriodEnd,
		&i.UpdatedAt,
	)
	return i, err
}
