// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comp.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearAssignedRoles = `-- name: ClearAssignedRoles :exec
UPDATE signups SET assigned_role = NULL
WHERE event_id = $1
`

// Locking any comp_name overwrites the whole event's assigned_role, since that
// column is single-valued while comp_slots holds multiple named drafts.
func (q *Queries) ClearAssignedRoles(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAssignedRoles, eventID)
	return err
}

const deleteComp = `-- name: DeleteComp :exec
DELETE FROM comps
WHERE event_id = $1 AND name = $2
`

type DeleteCompParams struct {
	EventID uuid.UUID
	Name    string
}

func (q *Queries) DeleteComp(ctx context.Context, arg DeleteCompParams) error {
	_, err := q.db.Exec(ctx, deleteComp, arg.EventID, arg.Name)
	return err
}

const deleteCompSlots = `-- name: DeleteCompSlots :exec
DELETE FROM comp_slots
WHERE event_id = $1 AND comp_name = $2
`

type DeleteCompSlotsParams struct {
	EventID  uuid.UUID
	CompName string
}

func (q *Queries) DeleteCompSlots(ctx context.Context, arg DeleteCompSlotsParams) error {
	_, err := q.db.Exec(ctx, deleteCompSlots, arg.EventID, arg.CompName)
	return err
}

const getComp = `-- name: GetComp :one
SELECT id, event_id, name, mode FROM comps
WHERE event_id = $1 AND name = $2
`

type GetCompParams struct {
	EventID uuid.UUID
	Name    string
}

func (q *Queries) GetComp(ctx context.Context, arg GetCompParams) (Comp, error) {
	row := q.db.QueryRow(ctx, getComp, arg.EventID, arg.Name)
	var i Comp
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Mode,
	)
	return i, err
}

const insertCompSlot = `-- name: InsertCompSlot :exec
INSERT INTO comp_slots (event_id, comp_name, character_id, role, slot_index, is_bench, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertCompSlotParams struct {
	EventID     uuid.UUID
	CompName    string
	CharacterID uuid.UUID
	Role        RoleEnum
	SlotIndex   int16
	IsBench     bool
	Reason      string
}

func (q *Queries) InsertCompSlot(ctx context.Context, arg InsertCompSlotParams) error {
	_, err := q.db.Exec(ctx, insertCompSlot,
		arg.EventID,
		arg.CompName,
		arg.CharacterID,
		arg.Role,
		arg.SlotIndex,
		arg.IsBench,
		arg.Reason,
	)
	return err
}

const listAssignmentPoolForEvent = `-- name: ListAssignmentPoolForEvent :many
SELECT
    s.character_id,
    c.name,
    c.is_main,
    c.ilvl,
    c.mplus_score,
    s.created_at AS signed_up_at
FROM signups s
JOIN characters c ON c.id = s.character_id
WHERE s.event_id = $1 AND s.status IN ('CONFIRMED', 'LATE')
ORDER BY s.created_at ASC, s.id ASC
`

type ListAssignmentPoolForEventRow struct {
	CharacterID uuid.UUID
	Name        string
	IsMain      bool
	Ilvl        pgtype.Numeric
	MplusScore  pgtype.Numeric
	SignedUpAt  pgtype.Timestamptz
}

// Confirmed and late signups only; declined, tentative, bench, absent, and no-show
// never reach the assigner.
func (q *Queries) ListAssignmentPoolForEvent(ctx context.Context, eventID uuid.UUID) ([]ListAssignmentPoolForEventRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentPoolForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentPoolForEventRow
	for rows.Next() {
		var i ListAssignmentPoolForEventRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Name,
			&i.IsMain,
			&i.Ilvl,
			&i.MplusScore,
			&i.SignedUpAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSlots = `-- name: ListCompSlots :many
SELECT id, event_id, comp_name, character_id, role, slot_index, is_bench, reason FROM comp_slots
WHERE event_id = $1 AND comp_name = $2
ORDER BY is_bench, slot_index
`

type ListCompSlotsParams struct {
	EventID  uuid.UUID
	CompName string
}

func (q *Queries) ListCompSlots(ctx context.Context, arg ListCompSlotsParams) ([]CompSlot, error) {
	rows, err := q.db.Query(ctx, listCompSlots, arg.EventID, arg.CompName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSlot
	for rows.Next() {
		var i CompSlot
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CompName,
			&i.CharacterID,
			&i.Role,
			&i.SlotIndex,
			&i.IsBench,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComps = `-- name: ListComps :many
SELECT id, event_id, name, mode FROM comps
WHERE event_id = $1
ORDER BY name
`

func (q *Queries) ListComps(ctx context.Context, eventID uuid.UUID) ([]Comp, error) {
	rows, err := q.db.Query(ctx, listComps, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comp
	for rows.Next() {
		var i Comp
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForCharacters = `-- name: ListRolesForCharacters :many
SELECT character_id, role, priority FROM character_roles
WHERE character_id = ANY($1::uuid[])
ORDER BY character_id, priority, role
`

func (q *Queries) ListRolesForCharacters(ctx context.Context, characterIds []uuid.UUID) ([]CharacterRole, error) {
	rows, err := q.db.Query(ctx, listRolesForCharacters, characterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterRole
	for rows.Next() {
		var i CharacterRole
		if err := rows.Scan(&i.CharacterID, &i.Role, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCompMode = `-- name: SetCompMode :exec
UPDATE comps SET mode = $3
WHERE event_id = $1 AND name = $2
`

type SetCompModeParams struct {
	EventID uuid.UUID
	Name    string
	Mode    CompMode
}

func (q *Queries) SetCompMode(ctx context.Context, arg SetCompModeParams) error {
	_, err := q.db.Exec(ctx, setCompMode, arg.EventID, arg.Name, arg.Mode)
	return err
}

const setSignupAssignedRole = `-- name: SetSignupAssignedRole :exec
UPDATE signups SET assigned_role = $3
WHERE event_id = $1 AND character_id = $2
`

type SetSignupAssignedRoleParams struct {
	EventID      uuid.UUID
	CharacterID  uuid.UUID
	AssignedRole *RoleEnum
}

func (q *Queries) SetSignupAssignedRole(ctx context.Context, arg SetSignupAssignedRoleParams) error {
	_, err := q.db.Exec(ctx, setSignupAssignedRole, arg.EventID, arg.CharacterID, arg.AssignedRole)
	return err
}

const upsertComp = `-- name: UpsertComp :one
INSERT INTO comps (event_id, name, mode)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, name) DO UPDATE SET name = excluded.name
RETURNING id, event_id, name, mode
`

type UpsertCompParams struct {
	EventID uuid.UUID
	Name    string
	Mode    CompMode
}

// Creating a comp is idempotent, but the mode is set once at creation: flipping an
// existing comp between AUTO and MANUAL is SetCompMode's job, so a stray create
// cannot quietly hand a raid lead's hand-built comp back to the assigner.
func (q *Queries) UpsertComp(ctx context.Context, arg UpsertCompParams) (Comp, error) {
	row := q.db.QueryRow(ctx, upsertComp, arg.EventID, arg.Name, arg.Mode)
	var i Comp
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Mode,
	)
	return i, err
}
