// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guildcatalog.sql

package db

import (
	"context"
)

const deleteGuildChannels = `-- name: DeleteGuildChannels :exec
DELETE FROM guild_channels
WHERE discord_guild_id = $1
`

func (q *Queries) DeleteGuildChannels(ctx context.Context, discordGuildID int64) error {
	_, err := q.db.Exec(ctx, deleteGuildChannels, discordGuildID)
	return err
}

const deleteGuildRoles = `-- name: DeleteGuildRoles :exec
DELETE FROM guild_roles
WHERE discord_guild_id = $1
`

func (q *Queries) DeleteGuildRoles(ctx context.Context, discordGuildID int64) error {
	_, err := q.db.Exec(ctx, deleteGuildRoles, discordGuildID)
	return err
}

const highestGuildRole = `-- name: HighestGuildRole :one
SELECT discord_role_id FROM guild_roles
WHERE discord_guild_id = $1 AND discord_role_id <> discord_guild_id
ORDER BY position DESC, discord_role_id DESC
LIMIT 1
`

// The top of the guild's role hierarchy, which is the one raid-lead mapping that may
// never be removed. Ties break on id so the answer does not move between calls.
//
// The bot already leaves @everyone and integration-managed roles out of this catalogue,
// so this filter is belt rather than braces. It is here because the two ship on separate
// cycles: an older bot that pushed @everyone would make it the guild's highest role, and
// pinning that as a raid-lead role hands the capability to every member.
func (q *Queries) HighestGuildRole(ctx context.Context, discordGuildID int64) (int64, error) {
	row := q.db.QueryRow(ctx, highestGuildRole, discordGuildID)
	var discord_role_id int64
	err := row.Scan(&discord_role_id)
	return discord_role_id, err
}

const insertGuildChannel = `-- name: InsertGuildChannel :exec
INSERT INTO guild_channels (discord_guild_id, discord_channel_id, name, type)
VALUES ($1, $2, $3, $4)
`

type InsertGuildChannelParams struct {
	DiscordGuildID   int64
	DiscordChannelID int64
	Name             string
	Type             DiscordChannelType
}

func (q *Queries) InsertGuildChannel(ctx context.Context, arg InsertGuildChannelParams) error {
	_, err := q.db.Exec(ctx, insertGuildChannel,
		arg.DiscordGuildID,
		arg.DiscordChannelID,
		arg.Name,
		arg.Type,
	)
	return err
}

const insertGuildRole = `-- name: InsertGuildRole :exec
INSERT INTO guild_roles (discord_guild_id, discord_role_id, name, color, position)
VALUES ($1, $2, $3, $4, $5)
`

type InsertGuildRoleParams struct {
	DiscordGuildID int64
	DiscordRoleID  int64
	Name           string
	Color          int32
	Position       int32
}

func (q *Queries) InsertGuildRole(ctx context.Context, arg InsertGuildRoleParams) error {
	_, err := q.db.Exec(ctx, insertGuildRole,
		arg.DiscordGuildID,
		arg.DiscordRoleID,
		arg.Name,
		arg.Color,
		arg.Position,
	)
	return err
}

const listGuildChannels = `-- name: ListGuildChannels :many
SELECT discord_channel_id, name, type FROM guild_channels
WHERE discord_guild_id = $1
ORDER BY name
`

type ListGuildChannelsRow struct {
	DiscordChannelID int64
	Name             string
	Type             DiscordChannelType
}

func (q *Queries) ListGuildChannels(ctx context.Context, discordGuildID int64) ([]ListGuildChannelsRow, error) {
	rows, err := q.db.Query(ctx, listGuildChannels, discordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuildChannelsRow
	for rows.Next() {
		var i ListGuildChannelsRow
		if err := rows.Scan(&i.DiscordChannelID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildRoles = `-- name: ListGuildRoles :many
SELECT discord_role_id, name, color, position FROM guild_roles
WHERE discord_guild_id = $1
ORDER BY position DESC
`

type ListGuildRolesRow struct {
	DiscordRoleID int64
	Name          string
	Color         int32
	Position      int32
}

func (q *Queries) ListGuildRoles(ctx context.Context, discordGuildID int64) ([]ListGuildRolesRow, error) {
	rows, err := q.db.Query(ctx, listGuildRoles, discordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuildRolesRow
	for rows.Next() {
		var i ListGuildRolesRow
		if err := rows.Scan(
			&i.DiscordRoleID,
			&i.Name,
			&i.Color,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
