// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJobsForEvent = `-- name: CancelJobsForEvent :exec
UPDATE scheduled_jobs SET status = 'CANCELED'
WHERE event_id = $1 AND status = 'PENDING'
`

func (q *Queries) CancelJobsForEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelJobsForEvent, eventID)
	return err
}

const claimDueJobs = `-- name: ClaimDueJobs :many
SELECT id, event_id, job_type, run_at, status, attempts FROM scheduled_jobs
WHERE status = 'PENDING' AND run_at <= now()
ORDER BY run_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimDueJobs(ctx context.Context, rowLimit int32) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, claimDueJobs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.JobType,
			&i.RunAt,
			&i.Status,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE scheduled_jobs SET status = $2, attempts = attempts + 1
WHERE id = $1
`

type MarkJobFailedParams struct {
	ID     uuid.UUID
	Status JobStatus
}

// Caller decides PENDING (retry) or FAILED (give up) based on the attempts it read
// off the claimed row; this just records the attempt.
func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.Exec(ctx, markJobFailed, arg.ID, arg.Status)
	return err
}

const markJobSent = `-- name: MarkJobSent :exec
UPDATE scheduled_jobs SET status = 'SENT'
WHERE id = $1
`

func (q *Queries) MarkJobSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markJobSent, id)
	return err
}

const scheduleJob = `-- name: ScheduleJob :exec
INSERT INTO scheduled_jobs (event_id, job_type, run_at)
VALUES ($1, $2, $3)
`

type ScheduleJobParams struct {
	EventID uuid.UUID
	JobType JobEnum
	RunAt   pgtype.Timestamptz
}

func (q *Queries) ScheduleJob(ctx context.Context, arg ScheduleJobParams) error {
	_, err := q.db.Exec(ctx, scheduleJob, arg.EventID, arg.JobType, arg.RunAt)
	return err
}
