// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EventType string

const (
	EventTypeRAID       EventType = "RAID"
	EventTypeMYTHICPLUS EventType = "MYTHIC_PLUS"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType
	Valid     bool // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type JobEnum string

const (
	JobEnumSIGNUPDEADLINE JobEnum = "SIGNUP_DEADLINE"
	JobEnumREMINDER24H    JobEnum = "REMINDER_24H"
	JobEnumREMINDER1H     JobEnum = "REMINDER_1H"
	JobEnumCOMPNAG        JobEnum = "COMP_NAG"
)

func (e *JobEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobEnum(s)
	case string:
		*e = JobEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobEnum: %T", src)
	}
	return nil
}

type NullJobEnum struct {
	JobEnum JobEnum
	Valid   bool // Valid is true if JobEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobEnum), nil
}

type JobStatus string

const (
	JobStatusPENDING  JobStatus = "PENDING"
	JobStatusSENT     JobStatus = "SENT"
	JobStatusFAILED   JobStatus = "FAILED"
	JobStatusCANCELED JobStatus = "CANCELED"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type RoleEnum string

const (
	RoleEnumTANK   RoleEnum = "TANK"
	RoleEnumHEALER RoleEnum = "HEALER"
	RoleEnumMDPS   RoleEnum = "MDPS"
	RoleEnumRDPS   RoleEnum = "RDPS"
)

func (e *RoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleEnum(s)
	case string:
		*e = RoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleEnum: %T", src)
	}
	return nil
}

type NullRoleEnum struct {
	RoleEnum RoleEnum
	Valid    bool // Valid is true if RoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleEnum), nil
}

type SignupStatus string

const (
	SignupStatusCONFIRMED SignupStatus = "CONFIRMED"
	SignupStatusTENTATIVE SignupStatus = "TENTATIVE"
	SignupStatusDECLINED  SignupStatus = "DECLINED"
	SignupStatusLATE      SignupStatus = "LATE"
	SignupStatusBENCH     SignupStatus = "BENCH"
	SignupStatusABSENT    SignupStatus = "ABSENT"
	SignupStatusNOSHOW    SignupStatus = "NO_SHOW"
)

func (e *SignupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignupStatus(s)
	case string:
		*e = SignupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SignupStatus: %T", src)
	}
	return nil
}

type NullSignupStatus struct {
	SignupStatus SignupStatus
	Valid        bool // Valid is true if SignupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SignupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignupStatus), nil
}

type Character struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Name            string
	Realm           string
	Class           *string
	Spec            *string
	Ilvl            pgtype.Numeric
	MplusScore      pgtype.Numeric
	LastSynced      pgtype.Timestamptz
	IsMain          bool
	Region          string
	SyncAttemptedAt pgtype.Timestamptz
}

type CharacterRole struct {
	CharacterID uuid.UUID
	Role        RoleEnum
	Priority    int16
}

type CharacterSnapshot struct {
	ID          uuid.UUID
	CharacterID uuid.UUID
	CapturedAt  pgtype.Timestamptz
	Ilvl        pgtype.Numeric
	MplusScore  pgtype.Numeric
	Gear        []byte
}

type CompSlot struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	CompName    string
	CharacterID uuid.UUID
	Role        RoleEnum
	SlotIndex   int16
	IsBench     bool
}

type Event struct {
	ID             uuid.UUID
	DiscordGuildID int64
	Type           EventType
	Title          string
	StartsAt       pgtype.Timestamptz
	SignupDeadline pgtype.Timestamptz
	CompTemplate   []byte
	MessageID      *int64
	ChannelID      *int64
}

type ScheduledJob struct {
	ID       uuid.UUID
	EventID  uuid.UUID
	JobType  JobEnum
	RunAt    pgtype.Timestamptz
	Status   JobStatus
	Attempts int16
}

type Signup struct {
	ID           uuid.UUID
	EventID      uuid.UUID
	CharacterID  uuid.UUID
	Status       SignupStatus
	AssignedRole *RoleEnum
	LateUntil    pgtype.Timestamptz
	Note         *string
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID             uuid.UUID
	DiscordID      int64
	DiscordGuildID int64
	CreatedAt      pgtype.Timestamptz
}
