// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (discord_guild_id, event_id, kind, target_kind, discord_id, role_ids, channel_id, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertNotificationParams struct {
	DiscordGuildID int64
	EventID        uuid.UUID
	Kind           NotificationKind
	TargetKind     NotificationTarget
	DiscordID      *int64
	RoleIds        []int64
	ChannelID      *int64
	Payload        []byte
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.DiscordGuildID,
		arg.EventID,
		arg.Kind,
		arg.TargetKind,
		arg.DiscordID,
		arg.RoleIds,
		arg.ChannelID,
		arg.Payload,
	)
	return err
}

const listUndeliveredNotifications = `-- name: ListUndeliveredNotifications :many
SELECT id, discord_guild_id, event_id, kind, target_kind, discord_id, role_ids, channel_id, payload, created_at, delivered_at FROM notifications
WHERE delivered_at IS NULL
  AND ($1::bigint IS NULL OR discord_guild_id = $1)
ORDER BY created_at ASC
LIMIT $2
`

type ListUndeliveredNotificationsParams struct {
	GuildID  *int64
	RowLimit int32
}

func (q *Queries) ListUndeliveredNotifications(ctx context.Context, arg ListUndeliveredNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUndeliveredNotifications, arg.GuildID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.DiscordGuildID,
			&i.EventID,
			&i.Kind,
			&i.TargetKind,
			&i.DiscordID,
			&i.RoleIds,
			&i.ChannelID,
			&i.Payload,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :exec
UPDATE notifications SET delivered_at = now()
WHERE id = $1
`

func (q *Queries) MarkNotificationDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationDelivered, id)
	return err
}
