// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotifications = `-- name: ClaimNotifications :many
UPDATE notifications SET claimed_at = now()
WHERE id IN (
    SELECT n.id FROM notifications n
    WHERE n.delivered_at IS NULL
      AND (n.claimed_at IS NULL OR n.claimed_at < $1)
      AND ($2::bigint IS NULL OR n.discord_guild_id = $2)
    ORDER BY n.created_at ASC
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, discord_guild_id, event_id, kind, target_kind, discord_id, role_ids, channel_id, payload, created_at, delivered_at, claimed_at
`

type ClaimNotificationsParams struct {
	ClaimedBefore pgtype.Timestamptz
	GuildID       *int64
	RowLimit      int32
}

// Claiming, not just reading. The ack arrives in a later HTTP request, so no
// transaction can span send and ack and row locks cannot help: two bot replicas
// polling the same window would both read the same rows and DM every raider twice.
// Stamping claimed_at inside the same statement hands each row to one poller.
//
// claimed_before re-opens a lease so a bot that claimed rows and died still gets them
// redelivered. That keeps delivery at-least-once, which reminders tolerate; what it
// removes is the duplicate storm on every tick.
func (q *Queries) ClaimNotifications(ctx context.Context, arg ClaimNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, claimNotifications, arg.ClaimedBefore, arg.GuildID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.DiscordGuildID,
			&i.EventID,
			&i.Kind,
			&i.TargetKind,
			&i.DiscordID,
			&i.RoleIds,
			&i.ChannelID,
			&i.Payload,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (discord_guild_id, event_id, kind, target_kind, discord_id, role_ids, channel_id, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertNotificationParams struct {
	DiscordGuildID int64
	EventID        uuid.UUID
	Kind           NotificationKind
	TargetKind     NotificationTarget
	DiscordID      *int64
	RoleIds        []int64
	ChannelID      *int64
	Payload        []byte
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.DiscordGuildID,
		arg.EventID,
		arg.Kind,
		arg.TargetKind,
		arg.DiscordID,
		arg.RoleIds,
		arg.ChannelID,
		arg.Payload,
	)
	return err
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :execrows
UPDATE notifications SET delivered_at = now()
WHERE id = $1
  AND ($2::bigint IS NULL OR discord_guild_id = $2)
`

type MarkNotificationDeliveredParams struct {
	ID      uuid.UUID
	GuildID *int64
}

// guild_id is optional, and the two callers differ. The bot acks across every guild
// from behind the service key, so it passes NULL. Anything reached by a raider's
// interaction must pass their guild, or acking by id alone would let them silently
// suppress another guild's reminders. Returning the row count lets the caller tell
// "not yours or not found" from "done".
func (q *Queries) MarkNotificationDelivered(ctx context.Context, arg MarkNotificationDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationDelivered, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
