// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raidlead.sql

package db

import (
	"context"
)

const countRaidLeadRoles = `-- name: CountRaidLeadRoles :one
SELECT count(*) FROM guild_raid_lead_roles
WHERE discord_guild_id = $1
`

// Drives the bootstrap rule: a guild with no mapped roles treats Discord admins as
// raid leads, so a fresh install is never bricked.
func (q *Queries) CountRaidLeadRoles(ctx context.Context, discordGuildID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRaidLeadRoles, discordGuildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRaidLeadRoles = `-- name: DeleteRaidLeadRoles :exec
DELETE FROM guild_raid_lead_roles
WHERE discord_guild_id = $1
`

func (q *Queries) DeleteRaidLeadRoles(ctx context.Context, discordGuildID int64) error {
	_, err := q.db.Exec(ctx, deleteRaidLeadRoles, discordGuildID)
	return err
}

const insertRaidLeadRole = `-- name: InsertRaidLeadRole :exec
INSERT INTO guild_raid_lead_roles (discord_guild_id, discord_role_id)
VALUES ($1, $2)
ON CONFLICT (discord_guild_id, discord_role_id) DO NOTHING
`

type InsertRaidLeadRoleParams struct {
	DiscordGuildID int64
	DiscordRoleID  int64
}

func (q *Queries) InsertRaidLeadRole(ctx context.Context, arg InsertRaidLeadRoleParams) error {
	_, err := q.db.Exec(ctx, insertRaidLeadRole, arg.DiscordGuildID, arg.DiscordRoleID)
	return err
}

const listRaidLeadRoles = `-- name: ListRaidLeadRoles :many
SELECT discord_role_id FROM guild_raid_lead_roles
WHERE discord_guild_id = $1
ORDER BY discord_role_id
`

func (q *Queries) ListRaidLeadRoles(ctx context.Context, discordGuildID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listRaidLeadRoles, discordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var discord_role_id int64
		if err := rows.Scan(&discord_role_id); err != nil {
			return nil, err
		}
		items = append(items, discord_role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
