// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roster.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (user_id, name, realm, region, is_main)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, realm, class, spec, ilvl, mplus_score, last_synced, is_main, region, sync_attempted_at
`

type CreateCharacterParams struct {
	UserID uuid.UUID
	Name   string
	Realm  string
	Region string
	IsMain bool
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.UserID,
		arg.Name,
		arg.Realm,
		arg.Region,
		arg.IsMain,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Realm,
		&i.Class,
		&i.Spec,
		&i.Ilvl,
		&i.MplusScore,
		&i.LastSynced,
		&i.IsMain,
		&i.Region,
		&i.SyncAttemptedAt,
	)
	return i, err
}

const deleteCharacterRoles = `-- name: DeleteCharacterRoles :exec
DELETE FROM character_roles
WHERE character_id = $1
`

func (q *Queries) DeleteCharacterRoles(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacterRoles, characterID)
	return err
}

const getCharacterInGuild = `-- name: GetCharacterInGuild :one
SELECT c.id, c.user_id, c.name, c.realm, c.class, c.spec, c.ilvl, c.mplus_score, c.last_synced, c.is_main, c.region, c.sync_attempted_at FROM characters c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1 AND u.discord_guild_id = $2
`

type GetCharacterInGuildParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
}

func (q *Queries) GetCharacterInGuild(ctx context.Context, arg GetCharacterInGuildParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterInGuild, arg.ID, arg.DiscordGuildID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Realm,
		&i.Class,
		&i.Spec,
		&i.Ilvl,
		&i.MplusScore,
		&i.LastSynced,
		&i.IsMain,
		&i.Region,
		&i.SyncAttemptedAt,
	)
	return i, err
}

const getCharacterOwner = `-- name: GetCharacterOwner :one
SELECT u.discord_id FROM characters c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1 AND u.discord_guild_id = $2
`

type GetCharacterOwnerParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
}

// A signup write is "self, or raid lead": self means the caller's discord id owns
// the character, which the signup and late-request handlers cannot decide without
// this.
func (q *Queries) GetCharacterOwner(ctx context.Context, arg GetCharacterOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCharacterOwner, arg.ID, arg.DiscordGuildID)
	var discord_id int64
	err := row.Scan(&discord_id)
	return discord_id, err
}

const getUserByDiscord = `-- name: GetUserByDiscord :one
SELECT id, discord_id, discord_guild_id, created_at FROM users
WHERE discord_id = $1 AND discord_guild_id = $2
`

type GetUserByDiscordParams struct {
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) GetUserByDiscord(ctx context.Context, arg GetUserByDiscordParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscord, arg.DiscordID, arg.DiscordGuildID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordGuildID,
		&i.CreatedAt,
	)
	return i, err
}

const listCharacterRoles = `-- name: ListCharacterRoles :many
SELECT character_id, role, priority FROM character_roles
WHERE character_id = $1
ORDER BY priority, role
`

// Nothing stops two roles sharing a priority; role keeps the menu order stable.
func (q *Queries) ListCharacterRoles(ctx context.Context, characterID uuid.UUID) ([]CharacterRole, error) {
	rows, err := q.db.Query(ctx, listCharacterRoles, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterRole
	for rows.Next() {
		var i CharacterRole
		if err := rows.Scan(&i.CharacterID, &i.Role, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByDiscord = `-- name: ListCharactersByDiscord :many
SELECT c.id, c.user_id, c.name, c.realm, c.class, c.spec, c.ilvl, c.mplus_score, c.last_synced, c.is_main, c.region, c.sync_attempted_at FROM characters c
JOIN users u ON u.id = c.user_id
WHERE u.discord_id = $1 AND u.discord_guild_id = $2
ORDER BY c.name
`

type ListCharactersByDiscordParams struct {
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) ListCharactersByDiscord(ctx context.Context, arg ListCharactersByDiscordParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersByDiscord, arg.DiscordID, arg.DiscordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
			&i.Region,
			&i.SyncAttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByUser = `-- name: ListCharactersByUser :many
SELECT id, user_id, name, realm, class, spec, ilvl, mplus_score, last_synced, is_main, region, sync_attempted_at FROM characters
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListCharactersByUser(ctx context.Context, userID uuid.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
			&i.Region,
			&i.SyncAttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersDueForSync = `-- name: ListCharactersDueForSync :many
SELECT id, user_id, name, realm, class, spec, ilvl, mplus_score, last_synced, is_main, region, sync_attempted_at FROM characters
WHERE (last_synced IS NULL OR last_synced < $1)
  AND (sync_attempted_at IS NULL OR sync_attempted_at < $1)
ORDER BY sync_attempted_at ASC NULLS FIRST
LIMIT $2
`

type ListCharactersDueForSyncParams struct {
	StaleBefore pgtype.Timestamptz
	RowLimit    int32
}

// Oldest-attempted first so a backlog drains fairly instead of starving whoever is
// always at the bottom of an ID-ordered scan. Ordering by attempt rather than by
// last_synced keeps a character whose fetch keeps failing from holding the head of
// every batch.
func (q *Queries) ListCharactersDueForSync(ctx context.Context, arg ListCharactersDueForSyncParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersDueForSync, arg.StaleBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
			&i.Region,
			&i.SyncAttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersInGuild = `-- name: ListCharactersInGuild :many
SELECT c.id, c.user_id, c.name, c.realm, c.class, c.spec, c.ilvl, c.mplus_score, c.last_synced, c.is_main, c.region, c.sync_attempted_at FROM characters c
JOIN users u ON u.id = c.user_id
WHERE u.discord_guild_id = $1
ORDER BY c.name
`

func (q *Queries) ListCharactersInGuild(ctx context.Context, discordGuildID int64) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersInGuild, discordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
			&i.Region,
			&i.SyncAttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCharacterSyncAttempted = `-- name: MarkCharacterSyncAttempted :exec
UPDATE characters SET sync_attempted_at = now()
WHERE id = $1
`

// A failed fetch. last_synced stays put because the cached data did not get any
// fresher; only the queue position moves.
func (q *Queries) MarkCharacterSyncAttempted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCharacterSyncAttempted, id)
	return err
}

const setCharacterRole = `-- name: SetCharacterRole :exec
INSERT INTO character_roles (character_id, role, priority)
VALUES ($1, $2, $3)
ON CONFLICT (character_id, role) DO UPDATE SET priority = excluded.priority
`

type SetCharacterRoleParams struct {
	CharacterID uuid.UUID
	Role        RoleEnum
	Priority    int16
}

func (q *Queries) SetCharacterRole(ctx context.Context, arg SetCharacterRoleParams) error {
	_, err := q.db.Exec(ctx, setCharacterRole, arg.CharacterID, arg.Role, arg.Priority)
	return err
}

const touchCharacterSynced = `-- name: TouchCharacterSynced :exec
UPDATE characters SET last_synced = now(), sync_attempted_at = now()
WHERE id = $1
`

func (q *Queries) TouchCharacterSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCharacterSynced, id)
	return err
}

const updateCharacterFromSync = `-- name: UpdateCharacterFromSync :exec
UPDATE characters SET
    class = COALESCE($4, class),
    spec = COALESCE($5, spec),
    ilvl = $2,
    mplus_score = $3,
    last_synced = now(),
    sync_attempted_at = now()
WHERE id = $1
`

type UpdateCharacterFromSyncParams struct {
	ID         uuid.UUID
	Ilvl       pgtype.Numeric
	MplusScore pgtype.Numeric
	Class      *string
	Spec       *string
}

// COALESCE so a response missing class or spec leaves the stored value alone
// instead of blanking it.
func (q *Queries) UpdateCharacterFromSync(ctx context.Context, arg UpdateCharacterFromSyncParams) error {
	_, err := q.db.Exec(ctx, updateCharacterFromSync,
		arg.ID,
		arg.Ilvl,
		arg.MplusScore,
		arg.Class,
		arg.Spec,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (discord_id, discord_guild_id)
VALUES ($1, $2)
ON CONFLICT (discord_id, discord_guild_id) DO UPDATE SET discord_id = excluded.discord_id
RETURNING id, discord_id, discord_guild_id, created_at
`

type UpsertUserParams struct {
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.DiscordID, arg.DiscordGuildID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordGuildID,
		&i.CreatedAt,
	)
	return i, err
}
