// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roster.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (user_id, name, realm, is_main)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, realm, class, spec, ilvl, mplus_score, last_synced, is_main
`

type CreateCharacterParams struct {
	UserID uuid.UUID
	Name   string
	Realm  string
	IsMain bool
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.UserID,
		arg.Name,
		arg.Realm,
		arg.IsMain,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Realm,
		&i.Class,
		&i.Spec,
		&i.Ilvl,
		&i.MplusScore,
		&i.LastSynced,
		&i.IsMain,
	)
	return i, err
}

const deleteCharacterRoles = `-- name: DeleteCharacterRoles :exec
DELETE FROM character_roles
WHERE character_id = $1
`

func (q *Queries) DeleteCharacterRoles(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacterRoles, characterID)
	return err
}

const getCharacterInGuild = `-- name: GetCharacterInGuild :one
SELECT c.id, c.user_id, c.name, c.realm, c.class, c.spec, c.ilvl, c.mplus_score, c.last_synced, c.is_main FROM characters c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1 AND u.discord_guild_id = $2
`

type GetCharacterInGuildParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
}

func (q *Queries) GetCharacterInGuild(ctx context.Context, arg GetCharacterInGuildParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterInGuild, arg.ID, arg.DiscordGuildID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Realm,
		&i.Class,
		&i.Spec,
		&i.Ilvl,
		&i.MplusScore,
		&i.LastSynced,
		&i.IsMain,
	)
	return i, err
}

const getUserByDiscord = `-- name: GetUserByDiscord :one
SELECT id, discord_id, discord_guild_id, created_at FROM users
WHERE discord_id = $1 AND discord_guild_id = $2
`

type GetUserByDiscordParams struct {
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) GetUserByDiscord(ctx context.Context, arg GetUserByDiscordParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscord, arg.DiscordID, arg.DiscordGuildID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordGuildID,
		&i.CreatedAt,
	)
	return i, err
}

const listCharacterRoles = `-- name: ListCharacterRoles :many
SELECT character_id, role, priority FROM character_roles
WHERE character_id = $1
ORDER BY priority, role
`

// Nothing stops two roles sharing a priority; role keeps the menu order stable.
func (q *Queries) ListCharacterRoles(ctx context.Context, characterID uuid.UUID) ([]CharacterRole, error) {
	rows, err := q.db.Query(ctx, listCharacterRoles, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterRole
	for rows.Next() {
		var i CharacterRole
		if err := rows.Scan(&i.CharacterID, &i.Role, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByDiscord = `-- name: ListCharactersByDiscord :many
SELECT c.id, c.user_id, c.name, c.realm, c.class, c.spec, c.ilvl, c.mplus_score, c.last_synced, c.is_main FROM characters c
JOIN users u ON u.id = c.user_id
WHERE u.discord_id = $1 AND u.discord_guild_id = $2
ORDER BY c.name
`

type ListCharactersByDiscordParams struct {
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) ListCharactersByDiscord(ctx context.Context, arg ListCharactersByDiscordParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersByDiscord, arg.DiscordID, arg.DiscordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByUser = `-- name: ListCharactersByUser :many
SELECT id, user_id, name, realm, class, spec, ilvl, mplus_score, last_synced, is_main FROM characters
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListCharactersByUser(ctx context.Context, userID uuid.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCharacterRole = `-- name: SetCharacterRole :exec
INSERT INTO character_roles (character_id, role, priority)
VALUES ($1, $2, $3)
ON CONFLICT (character_id, role) DO UPDATE SET priority = excluded.priority
`

type SetCharacterRoleParams struct {
	CharacterID uuid.UUID
	Role        RoleEnum
	Priority    int16
}

func (q *Queries) SetCharacterRole(ctx context.Context, arg SetCharacterRoleParams) error {
	_, err := q.db.Exec(ctx, setCharacterRole, arg.CharacterID, arg.Role, arg.Priority)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (discord_id, discord_guild_id)
VALUES ($1, $2)
ON CONFLICT (discord_id, discord_guild_id) DO UPDATE SET discord_id = excluded.discord_id
RETURNING id, discord_id, discord_guild_id, created_at
`

type UpsertUserParams struct {
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.DiscordID, arg.DiscordGuildID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordGuildID,
		&i.CreatedAt,
	)
	return i, err
}
