// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signup.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty
`

type CreateEventParams struct {
	DiscordGuildID int64
	Type           EventType
	Title          string
	StartsAt       pgtype.Timestamptz
	SignupDeadline pgtype.Timestamptz
	CompTemplate   []byte
	MessageID      *int64
	ChannelID      *int64
	Difficulty     *RaidDifficulty
}

// difficulty is NULL for MYTHIC_PLUS events, which have no difficulty of their own.
// For a raid it decides the comp size rule, so the assigner cannot tell a Mythic
// raid from a flex one without it.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.DiscordGuildID,
		arg.Type,
		arg.Title,
		arg.StartsAt,
		arg.SignupDeadline,
		arg.CompTemplate,
		arg.MessageID,
		arg.ChannelID,
		arg.Difficulty,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordGuildID,
		&i.Type,
		&i.Title,
		&i.StartsAt,
		&i.SignupDeadline,
		&i.CompTemplate,
		&i.MessageID,
		&i.ChannelID,
		&i.Difficulty,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordGuildID,
		&i.Type,
		&i.Title,
		&i.StartsAt,
		&i.SignupDeadline,
		&i.CompTemplate,
		&i.MessageID,
		&i.ChannelID,
		&i.Difficulty,
	)
	return i, err
}

const listSignupsForEvent = `-- name: ListSignupsForEvent :many
SELECT id, event_id, character_id, status, assigned_role, late_until, note, created_at FROM signups
WHERE event_id = $1
ORDER BY created_at ASC, id ASC
`

// created_at is transaction start time, so it ties for signups written together.
func (q *Queries) ListSignupsForEvent(ctx context.Context, eventID uuid.UUID) ([]Signup, error) {
	rows, err := q.db.Query(ctx, listSignupsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Signup
	for rows.Next() {
		var i Signup
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CharacterID,
			&i.Status,
			&i.AssignedRole,
			&i.LateUntil,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty FROM events
WHERE discord_guild_id = $1 AND starts_at >= now()
ORDER BY starts_at ASC
`

func (q *Queries) ListUpcomingEvents(ctx context.Context, discordGuildID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents, discordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.DiscordGuildID,
			&i.Type,
			&i.Title,
			&i.StartsAt,
			&i.SignupDeadline,
			&i.CompTemplate,
			&i.MessageID,
			&i.ChannelID,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventDifficulty = `-- name: SetEventDifficulty :exec
UPDATE events SET difficulty = $2
WHERE id = $1
`

type SetEventDifficultyParams struct {
	ID         uuid.UUID
	Difficulty *RaidDifficulty
}

func (q *Queries) SetEventDifficulty(ctx context.Context, arg SetEventDifficultyParams) error {
	_, err := q.db.Exec(ctx, setEventDifficulty, arg.ID, arg.Difficulty)
	return err
}

const upsertSignup = `-- name: UpsertSignup :one
INSERT INTO signups (event_id, character_id, status, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id, character_id) DO UPDATE SET
    status = excluded.status,
    note = excluded.note,
    assigned_role = CASE
        WHEN signups.status IS DISTINCT FROM excluded.status THEN NULL
        ELSE signups.assigned_role
    END,
    late_until = CASE
        WHEN signups.status IS DISTINCT FROM excluded.status THEN NULL
        ELSE signups.late_until
    END
RETURNING id, event_id, character_id, status, assigned_role, late_until, note, created_at
`

type UpsertSignupParams struct {
	EventID     uuid.UUID
	CharacterID uuid.UUID
	Status      SignupStatus
	Note        *string
}

// A status change invalidates whatever the comp lock decided, so the assignment is
// dropped. Editing only the note leaves an existing assignment alone.
func (q *Queries) UpsertSignup(ctx context.Context, arg UpsertSignupParams) (Signup, error) {
	row := q.db.QueryRow(ctx, upsertSignup,
		arg.EventID,
		arg.CharacterID,
		arg.Status,
		arg.Note,
	)
	var i Signup
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CharacterID,
		&i.Status,
		&i.AssignedRole,
		&i.LateUntil,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
