name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tim-actions/dco@v1.1.0

  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: build
        run: go build ./...

      - name: test
        run: go test ./...

      - name: test-integration
        run: go test -tags=integration ./...

      - name: lint
        run: go tool golangci-lint run
